### ISSUE TITLE
how to use force.js error

### ISSUE THREAD

**Issue by ilovegame1985** [BeepFelix/CSGO-Overwatch-Bot#11]
C:\Users\Disha\Desktop\CSGO-Overwatch-Bot-master\CSGO-Overwatch-Bot-master>node force
? Enter the name of the demo: test
? Suspect SteamID: 0:0:861470***
File does not exist

can you explain how to do proper?

thank  you!

**Comment by BeepFelix** [comment]
Put the demo in the folder, put in the demo name when it asks, put in the SteamID64 of the person you want to check.

**Comment by ilovegame1985** [comment]
I already did but it said file does not exist

**Comment by BeepFelix** [comment]
Then it doesn't exist, you can read the code yourself [it checks if the file exists and if it doesn't then it just doesn't](https://github.com/BeepFelix/CSGO-Overwatch-Bot/blob/6e48751d6d0f5901b2c1d8663ef11e472998a2ab/force.js#L32).

Demo's end it `.dem` so make sure your file has the same ending.

**Comment by ilovegame1985** [comment]
Ty problem fixed
