### ISSUE TITLE
Failed to find protobufs

### ISSUE THREAD

**Issue by tkien212** [BeepFelix/CSGO-Overwatch-Bot#3]
E:\Downloads\Compressed\CSGO-Overwatch-Bot-master>npm install
audited 268 packages in 1.524s
found 0 vulnerabilities

E:\Downloads\Compressed\CSGO-Overwatch-Bot-master>node index.js
Steam Guard App Code: jy6d5
Successfully logged into 76xxxxxxxxxxxxxxx
Checking protobufs...
Failed to find protobufs, downloading and extracting...
A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...

**Comment by tkien212** [comment]
nvm just need to rename the folder
thanks for the bot

**Comment by rabi07** [comment]
hey same problm.. which folder i have to rename

**Comment by rabi07** [comment]
@tkien212

**Comment by BeepFelix** [comment]
> hey same problm.. which folder i have to rename

It should automatically download the protobufs it fails to find them.
