### ISSUE TITLE
How to check if bot said yes/no to overwatch case?

### ISSUE THREAD

**Issue by tkien212** [BeepFelix/CSGO-Overwatch-Bot#4]
i looked in the 'cases' folder and it always show verdict and reason = 0
Is there another way to check?

**Comment by BeepFelix** [comment]
Verdict and Reason are irrelevant as they are part of what Valve sends. You can only do this by counting the amount of infractions the user had and then using your config.json

**Comment by tkien212** [comment]
i see. thank you
