### ISSUE TITLE
A request failed to run. Github, Steam or CSGO might currently be offline

### ISSUE THREAD

**Issue by crx9** [BeepFelix/CSGO-Overwatch-Bot#5]
Establishing CSGO GameCoordinator connection...
A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...

why?

**Comment by BeepFelix** [comment]
Read it. Either one of those or your account doesn't have access to Overwatch.

**Comment by rabi07** [comment]
same problem. also, account have Overwatch  enable.

**Comment by BeepFelix** [comment]
Does it happen repeatedly? Only sometimes? Does it happen right now?

**Comment by rabi07** [comment]
YES IT ..HAPPENING EVERY TIME..
DO I HAVE TO CLOSE STEAM?

**Comment by rabi07** [comment]
it's working thanks
