### ISSUE TITLE
It happens from time to time

### ISSUE THREAD

**Issue by Slizza** [BeepFelix/CSGO-Overwatch-Bot#7]
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (D:\G\G12\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:210:5)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by BeepFelix** [comment]
Your internet broke and caused errors.

**Comment by Slizza** [comment]
Could this error accur becuase i run 20 of them at once?

**Comment by Slizza** [comment]
Ofc 20 different accounts
https://gyazo.com/83ad0795e3a808a5ab93a3be30c0544f

**Comment by BeepFelix** [comment]
It is possible that this is the problem. Your internet can't seem to handle this many connections.

**Comment by Slizza** [comment]
Is there any chance you create something like this(script who start multi overwatch bots with delays) for large amount of accounts?
Because right now i has to start 20+ cmds to launch.

**Comment by BeepFelix** [comment]
I don't play on doing this.

**Comment by Alexey25322** [comment]
> 
> 
> Is there any chance you create something like this(script who start multi overwatch bots with delays) for large amount of accounts?
> Because right now i have to start 20+ cmds to launch.

Just write a batch file / c# project which starts every instance for you.

**Comment by crx9** [comment]
> I don't play on doing this.

Checking for updates...
{ Error: connect ETIMEDOUT 69.171.248.128:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '69.171.248.128',
  port: 443 }
A new version is available on Github @ https://github.com/BeepFelix/CSGO-Overwatch-Bot
Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json"
Establishing CSGO GameCoordinator connection...
A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...

i used the latest version,but....

**Comment by Alexey25322** [comment]
> 
> 
> > I don't play on doing this.
> 
> Checking for updates...
> { Error: connect ETIMEDOUT 69.171.248.128:443
> at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
> errno: 'ETIMEDOUT',
> code: 'ETIMEDOUT',
> syscall: 'connect',
> address: '69.171.248.128',
> port: 443 }
> A new version is available on Github @ https://github.com/BeepFelix/CSGO-Overwatch-Bot
> Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json"
> Establishing CSGO GameCoordinator connection...
> A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...
> 
> i used the latest version,but....

When you updadted the last time, which files did you replace?

**Comment by crx9** [comment]
I just downloaded the complete package on gitHub

**Comment by crx9** [comment]
> > > I don't play on doing this.
> > 
> > 
> > Checking for updates... { Error: connect ETIMEDOUT 69.171.248.128:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'connect', address: '69.171.248.128', port: 443 } A new version is available on Github @ https://github.com/BeepFelix/CSGO-Overwatch-Bot Downloading is optional but recommended. Make sure to check if there are any new values to be added in your old "config.json" Establishing CSGO GameCoordinator connection... A request failed to run. Github, Steam or CSGO might currently be offline. Logging out...
> > i used the latest version,but....
> 
> When you updadted the last time, which files did you replace?

I just downloaded the complete package on gitHub

**Comment by BeepFelix** [comment]
Any request the bot makes fails. Your internet is at fault.
